title: Qianli Hu @ Georgia Tech

email: qianli-hu@math.gatech.edu
github: http://github.com/qianli-hu
# linkedin: https://www.linkedin.com/in/ruilin-li-b71448bb/
office: Room 152, Skiles Building, 686 Cherry St

markdown: kramdown

baseurl: /qianli-hu.github.io

remoteurl: https://github.com/qianli-hu.github.io

exclude: ['README.md']
