title: Ruilin Li  &middot;  Machine Learning @ Georgia Tech

email: ruilin.li@gatech.edu
github: http://github.com/ruilin-li
linkedin: https://www.linkedin.com/in/ruilin-li-b71448bb/
office: Room 146B, Skiles Building, 686 Cherry St

markdown: kramdown

baseurl: /ruilin-li

remoteurl: https://github.com/ruilin-li.github.io

exclude: ['README.md']